version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ex_cldr" # TODO: https://github.com/change/linguist/pull/33
    labels:
      - "mix dependencies"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "docker dependencies"
