version: 2
enabled: false
updates:
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: daily
    labels:
    - mix
    - dependencies

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
    - docker
    - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
    - ci
