require: rubocop-rspec

AllCops:
  Exclude:
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - bin/**/*
    - vendor/bundle/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
Rails:
  Enabled: true
Rails/InverseOf:
  Enabled: false
Rails/ActiveRecordAliases:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/LineLength:
  Max: 150
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Style/RescueStandardError:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/Next:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
RSpec/ExampleLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10
RSpec/ContextWording:
  Prefixes:
  - with
  - without
  - when
  - if
  - is
RSpec/NestedGroups:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
