FROM dolfinus/arkenston-backend:build
ENV MIX_ENV dev

COPY --chown=root:root entrypoint.dev.sh wait_for_postgres.sh ./
RUN chmod +x ./entrypoint* ./wait_for_postgres.sh
ENTRYPOINT ["./entrypoint.dev.sh"]
