FROM bitwalker/alpine-elixir:1.9.1

RUN apk add --update --no-cache \
  bash \
  postgresql-client \
  yaml-dev \
  tzdata \
  sudo

RUN mkdir -p /arkenston && adduser -u 2000 -h /arkenston -s /bin/bash -D arkenston
WORKDIR /arkenston

COPY --chown=arkenston:arkenston mix.* ./

RUN mix do local.hex --force, local.rebar --force