version: '3.6'
services:
  db_test:
    image: postgres:alpine
    container_name: db_test
    env_file: .env.test
    networks:
      - db
  backend_test:
    image: dolfinus/arkenston-backend:test
    container_name: backend_test
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - ./mix.exs:/arkenston/mix.exs
      - ./mix.lock:/arkenston/mix.lock
      - ./_build:/arkenston/_build
      - ./deps:/arkenston/deps
      - ./config:/arkenston/config
      - ./lib:/arkenston/lib
      - ./priv:/arkenston/priv
      - ./test:/arkenston/test
    env_file: .env.test
    environment:
      - CI="$CI"
      - TRAVIS="$TRAVIS"
      - TRAVIS_JOB_ID="$TRAVIS_JOB_ID"
      - TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    networks:
      - db
      - public
networks:
  db:
    internal: true
  public: