version: '3.6'
services:
  db:
    image: postgres:alpine
    container_name: db
    env_file: .env
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  arkenston:
    image: dolfinus/arkenston-backend:latest
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - db
      - public
networks:
  db:
    internal: true
    name: db
  public:
