FROM dolfinus/arkenston-backend:build
ENV MIX_ENV dev
RUN mix deps.get --only dev

COPY --chown=arkenston:arkenston config/ ./config/
COPY --chown=arkenston:arkenston lib/    ./lib/
COPY --chown=arkenston:arkenston priv/   ./priv/
RUN mix deps.compile

COPY --chown=root:root entrypoint.dev.sh wait_for_postgres.sh ./
RUN chmod +x ./entrypoint* ./wait_for_postgres.sh
ENTRYPOINT ["./entrypoint.dev.sh"]
