FROM dolfinus/arkenston-backend:base
ENV MIX_ENV prod
RUN \
  apk add --update --virtual build-dependencies build-base && \
  mix do deps.get --only prod, deps.compile --force && \
  apk del build-dependencies