version: '3.6'
services:
  db_dev:
    image: postgres:alpine
    container_name: db_dev
    env_file: .env.dev
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  backend_dev:
    image: dolfinus/arkenston-backend:dev
    container_name: backend_dev
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./mix.exs:/arkenston/mix.exs
      - ./mix.lock:/arkenston/mix.lock
      - ./_build:/arkenston/_build
      - ./deps:/arkenston/deps
      - ./config:/arkenston/config
      - ./lib:/arkenston/lib
      - ./priv:/arkenston/priv
    ports:
      - 3001:3000
    env_file: .env.dev
    networks:
      - db
      - public
networks:
  db:
    internal: true
  public: