FROM bitwalker/alpine-elixir:1.9.1

RUN apk add --update --no-cache \
  bash \
  postgresql-client \
  yaml-dev \
  tzdata \
  make \
  sudo

RUN mkdir -p /opt/app && adduser -u 2000 -h /opt/app -s /bin/bash -D arkenston
WORKDIR /opt/app

COPY --chown=arkenston:arkenston mix.* ./

RUN mix do local.hex --force, local.rebar --force