version: '3.6'
services:
  db_test:
    image: postgres:alpine
    container_name: db_test
    env_file: .env.test
    networks:
      - db
  backend_test:
    image: dolfinus/arkenston-backend:test
    container_name: backend_test
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./spec:/opt/app/spec
      - ./coverage:/opt/app/cover
      - ./mix.exs:/opt/app/mix.exs
      - ./mix.lock:/opt/app/mix.lock
      - ./.iex.exs:/opt/app/.iex.exs
      - ./erlang-history:/opt/app/.cache/erlang-history
    env_file: .env.test
    environment:
      - CI="$CI"
      - TRAVIS="$TRAVIS"
      - TRAVIS_JOB_ID="$TRAVIS_JOB_ID"
      - TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    networks:
      - default
      - db
networks:
  db:
    internal: true
