version: '3.6'
services:
  db_prod:
    image: postgres:alpine
    container_name: db_prod
    env_file: .env.prod
    networks:
      - db
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  arkenston_prod:
    image: dolfinus/arkenston-backend:latest
    container_name: backend_prod
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - 3000:3000
    env_file: .env.prod
    networks:
      - default
      - db
networks:
  db:
    internal: true
    name: db
