default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>
  user: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
