token:
  default: &default
    algorithm: HS256
  refresh:
    <<: *default
    expire: <%= 1.month %>
  access:
    <<: *default
    expire: <%= 1.hour %>
graphql:
  max_depth: 10
  max_page_size: 50
  max_complexity: 100
  schema:
    json: app/graphql/schema.json
    dsl: app/graphql/schema.graphql
  docs:
    output: public/docs
users:
  name:
    format: '[a-zA-Z0-9_\.]+'
  admin:
    name: admin
    role: admin
    email: admin@example.com
    password: 12345678
  anonymous:
    name: anonymous
    id: -1